### ISSUE TITLE
Selection in rename box doesn't show

### ISSUE THREAD

**Issue by Tyriar** [pveyes/aperture#3]
Looks like the color must be the same as the background or transparent? Repro is to f2 a symbol and try to select part of the symbol.

<img width="226" alt="Screen Shot 2021-06-16 at 6 28 40 PM" src="https://user-images.githubusercontent.com/2193314/122316410-add6ff80-ced0-11eb-98d8-e503154e65f4.png">

**Comment by pveyes** [comment]
You're right, this is unexpected. Will fix this to use default blue
